version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: deoroatelier_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: DoaJewelry
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
          - ./sql:/docker-entrypoint-initdb.d:ro
