services:
  postgres:
    image: postgres:15
    container_name: doajewelry_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: doajewelry
    ports:
      - "5433:5432"
  app:
    build:
      context: .
    container_name: doajewelry_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/doajewelry
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
